// <auto-generated />
using System;
using AddressBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AddressBook.Data.Migrations
{
    [DbContext(typeof(AddressBookDbContext))]
    partial class AddressBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AddressBook.Core.AddressBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("AddressBooks");
                });

            modelBuilder.Entity("AddressBook.Core.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AddressBookId");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Name");

                    b.Property<int>("Tracking");

                    b.HasKey("Id");

                    b.HasIndex("AddressBookId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("AddressBook.Core.TelephoneNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ContactId");

                    b.Property<int>("Tracking");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("TelephoneNumber");
                });

            modelBuilder.Entity("AddressBook.Core.Contact", b =>
                {
                    b.HasOne("AddressBook.Core.AddressBook")
                        .WithMany("Contacts")
                        .HasForeignKey("AddressBookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("AddressBook.Core.Address", "Address", b1 =>
                        {
                            b1.Property<Guid?>("ContactId");

                            b1.Property<string>("City");

                            b1.Property<string>("Country");

                            b1.Property<string>("Street");

                            b1.Property<string>("StreetNr");

                            b1.ToTable("Contact");

                            b1.HasOne("AddressBook.Core.Contact")
                                .WithOne("Address")
                                .HasForeignKey("AddressBook.Core.Address", "ContactId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("AddressBook.Core.TelephoneNumber", b =>
                {
                    b.HasOne("AddressBook.Core.Contact")
                        .WithMany("TelephoneNumbers")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
